spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cars_database
    driverClassName: org.postgresql.Driver
    username: difelix
    password: 123456
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  packagesToScan: com.difelix.cardatabase.controllers