version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: difelix
      POSTGRES_DB: cars_database
    ports:
      - 5432:5432